/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChangeBadge: typeof import('./components/ChangeBadge.vue')['default']
    FilterBar: typeof import('./components/FilterBar.vue')['default']
    LocaleSwitch: typeof import('./components/LocaleSwitch.vue')['default']
    MarkdownText: typeof import('./components/MarkdownText.vue')['default']
    ProgramCard: typeof import('./components/ProgramCard.vue')['default']
    ProgramDetails: typeof import('./components/ProgramDetails.vue')['default']
    ProgramList: typeof import('./components/ProgramList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SourceStatusBar: typeof import('./components/SourceStatusBar.vue')['default']
    SummaryTaskStack: typeof import('./components/SummaryTaskStack.vue')['default']
    Tabs: typeof import('./components/Tabs.vue')['default']
  }
}
